# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# how to solve?
# 1. generate Fibonacci sequence limited by 4,000,000
# 2. find the sum of the even-valued terms

# seq = [1, 2]
# for i in range(100):
#     new_seq = seq[i] + seq[i + 1]
#     if new_seq > 4000000 :
#         print(i)
#         break
#     seq.append(new_seq)
# print(seq)

# by this solution, I find out seqence range limit is 30

seq = [1, 2]
for i in range(30):
    new_seq = seq[i] + seq[i + 1]
    seq.append(new_seq)

result = 0
for j in seq:
    if j % 2 == 0:
        result += j
print(result)
