# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

import time
start = time.time()

def penta(x):
    return x*(3*x-1)//2

pentas = []
sieve = set(pentas)
k = 1

while True:
    pk = penta(k)
    for pn in pentas:
        pk_n = pk - pn
        d = abs(pn - pk_n)
        
        if pk_n in sieve and d in sieve:
            print(d)
            end = time.time()
            print(end-start)
    
    pentas.append(pk)
    sieve.add(pk)
    k += 1
