# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

# 1. compare leading coefficient for deciding standard

# 2. Tri : 1/2, Penta : 3/2, Hexa : 2

import time
start = time.time()

def tri(x):
    return x*(x+1)//2
def penta(x):
    return x*(3*x-1)//2
def hexa(x):
    return x*(2*x-1)

tris = set()
pentas = set()
hexas = set()

n = 143
while True:
    tri_n = tri(n)
    tris.add(tri_n)
    pentas.add(penta(n))
    hexas.add(hexa(n))

    if tri_n in hexas and tri_n in pentas and tri_n > 40755:
        print(n, tri_n)
        end = time.time()
        print(end - start)
        break
    n += 1